---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 11, fig.height = 9)
options(digits = 6, scipen = 6)
```

# Wykres

```{r, echo=FALSE}
source("../other_algorithms/CapacityScaling.R")
source("../other_algorithms/SimpleGreedy.R")
source("../other_algorithms/fixedpi.R")
source("../R/algorithms_twosided.R")
source("../R/plots.R")

library(checkmate)
library(ggplot2)

seed <- 5

set.seed(seed)
ind <- sample(1:nrow(stratallo::pop507), 30)
N <- stratallo::pop507[ind, 1]
S <- stratallo::pop507[ind, 2]
a <- N * S

M <- N
set.seed(seed)
m <- sapply(M, function(i) sample(floor(0.8*i), 1))
n <- floor(sum(m) + (sum(M) - sum(m)) * 0.0001)

n <- 15837
opt <- rna_box_debug(n, a, m, M)
alloc0 <- CapacityScaling(n, N, S, m, M)
#max(abs(opt$opt - alloc0)) <= 1
(p <- plot_rnabox(opt$UL, a, m, M, n = n / sum(N)))

ggplot2::ggsave(filename = "rnabox_choinka_H30.pdf", device = "pdf")

```

# Przykladowa populacja wraz z alokacja optymalna dla ustalonego n = `r n`.

```{r out1, echo=FALSE}

dat <- data.frame(a = a, m = m, M = M, opt = opt$opt)
dat$`take-min` <- ifelse(dat$opt == m, "*", "")
dat$`take-max` <- ifelse(dat$opt == M, "*", "")
dat$`take-Neyman` <- ifelse(dat$opt != m & dat$opt != M, "*", "")
dat <- rbind(
  dat,
  c(NA, sum(m), sum(M), sum(opt$opt), sum(dat$opt == m), sum(dat$opt == M), sum(dat$opt != m & dat$opt != M))
)
rownames(dat) <- c(paste0("Strata_", 1:length(a)), "SUM")
dat
```

# Wartosci funkcji s() dla kazdej z iteracji

```{r out2, echo=FALSE}

m_order <- c(0, order(a / m, decreasing = FALSE))
M_order <- c(0, order(a / M, decreasing = TRUE))

data_p <- lapply(opt$UL, function(i) {
  c(length(i$L_cum), length(i$U_rna), i$s0, i$s)
})
data_p <- data.frame(do.call(rbind, data_p))
colnames(data_p) <- c("L_cum_size", "U_rna_size", "s(L_cum, 0)", "s(L_cum, U_rna)")
rownames(data_p) <- paste0("Iteration_", seq_len(nrow(data_p)))
data_p
```

# Szczegoly w kazdej z iteracji

```{r out3, echo=FALSE}
names(opt$UL) <- paste("Iteracja ", 1:length(opt$UL))
opt$UL
```
